services:
    app:
        container_name: flash-sale-app
        build:
            context: .
            dockerfile: Dockerfile
        image: flash-sale/laravel-frankenphp
        ports:
            - "${APP_PORT:-8080}:${APP_PORT:-8080}"
            - "${VITE_PORT:-5173}:5173"
        environment:
            APP_URL: "http://localhost:8080"
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
            AUTO_MIGRATE: ${AUTO_MIGRATE:-true}
            GENERATE_ENV: ${GENERATE_ENV:-true}
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: "${DB_DATABASE}"
            DB_USERNAME: "${DB_USERNAME}"
            DB_PASSWORD: "${DB_PASSWORD}"
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
              - ./app:/var/www/html/app
              - ./resources:/var/www/html/resources
              - ./routes:/var/www/html/routes
              - ./database:/var/www/html/database
        restart: unless-stopped
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - flash-sale

    mysql:
        container_name: flash-sale-mysql
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - "${FORWARD_DB_PORT:-3307}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - flash-sale
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 5

    redis:
        container_name: flash-sale-redis
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - redis-data:/data
        networks:
            - flash-sale
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 5

    phpmyadmin:
        container_name: flash-sale-phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "${PMA_PORT:-81}:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: "${DB_USERNAME}"
            PMA_PASSWORD: "${DB_PASSWORD}"
            UPLOAD_LIMIT: 100M
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - flash-sale

networks:
    flash-sale:
        driver: bridge

volumes:
    mysql-data:
    redis-data:
